-- 0008_bonding_succession.sql
-- Agent Bonding (surety-bond-as-signal) + Successions / Dead Man's Switch.
--
-- Adds three new tables (successions, bonds, bond_underwriters) and the
-- denormalized wallets columns that drive the Agent Estates dashboard and the
-- orthogonal Surety Karma axis. Generated by hand from src/db/schema.ts in the
-- style of 0006_celo_agent_id.sql / 0007_arc_agent_id.sql (BEGIN/COMMIT, every
-- DDL guarded with IF NOT EXISTS so the migration is idempotent and re-runnable).
--
-- INVARIANTS encoded structurally here:
--   * Every (chain, agent_wallet) / (chain, underwriter_wallet) reference is a
--     composite FK onto wallets (chain, address) with ON DELETE CASCADE, matching
--     the multichain composite-PK convention (see 0004_multichain.sql).
--   * is_demo on bonds is the durable demo marker — scoring EXCLUDES is_demo rows
--     from real scores; the column defaults to false so backfilled real escrows
--     are never accidentally hidden.
--   * Successions are one-per-agent: PK (chain, agent_wallet). The resolver
--     overwrites on re-declaration.
--   * Bonds dedup on (chain, escrow_ref) via a unique index — re-indexing the
--     same escrow event is a no-op upsert target.
--   * Surety Karma columns are ORTHOGONAL — never blended into Provider/Consumer.
--
-- NOTE (non-custody / non-routing): these tables are AK's READ-ONLY projection
-- of public escrow + will lifecycles. No column holds a key or moves funds.
--
-- Founder runs `bun db:push` after review. The project does NOT track a drizzle
-- meta journal/snapshot (drizzle/meta/ does not exist; see drizzle.config.ts),
-- so there is nothing to update beyond this SQL file.

BEGIN;

-- --- wallets: denormalized succession + orthogonal surety columns ------------

ALTER TABLE wallets
  ADD COLUMN IF NOT EXISTS succession_status          text,
  ADD COLUMN IF NOT EXISTS heartbeat_last_at          timestamptz,
  ADD COLUMN IF NOT EXISTS heartbeat_interval_seconds integer,
  ADD COLUMN IF NOT EXISTS surety_score               numeric(6, 2),
  ADD COLUMN IF NOT EXISTS surety_label               text;

CREATE INDEX IF NOT EXISTS idx_wallets_succession_status
  ON wallets (succession_status);
CREATE INDEX IF NOT EXISTS idx_wallets_surety_score
  ON wallets (surety_score);

-- --- successions / Dead Man's Switch (Agent Wills) ---------------------------
-- One will per (chain, agent_wallet). will_hash + on-chain witness fields stay
-- NULL in the no-contract MVP.

CREATE TABLE IF NOT EXISTS successions (
  chain             text        NOT NULL DEFAULT 'solana',
  agent_wallet      text        NOT NULL,
  source_type       text        NOT NULL,
  interval_seconds  integer     NOT NULL,
  heirs             jsonb       NOT NULL,
  status            text        NOT NULL DEFAULT 'declared',
  will_hash         text,
  declared_at       timestamptz NOT NULL DEFAULT now(),
  last_heartbeat_at timestamptz,
  lapsed_at         timestamptz,
  executed_at       timestamptz,
  revoked_at        timestamptz,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT successions_pkey PRIMARY KEY (chain, agent_wallet),
  CONSTRAINT successions_chain_agent_wallet_fkey
    FOREIGN KEY (chain, agent_wallet)
    REFERENCES wallets (chain, address)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_successions_status
  ON successions (status);
CREATE INDEX IF NOT EXISTS idx_successions_last_heartbeat_at
  ON successions (last_heartbeat_at);

-- --- bonds / Agent Bonding (surety-bond-as-signal) --------------------------
-- AK's read-only projection of a third-party escrow's public lifecycle. is_demo
-- flags seeded/preview rows; scoring excludes them from real scores.

CREATE TABLE IF NOT EXISTS bonds (
  id                  uuid           PRIMARY KEY DEFAULT gen_random_uuid(),
  chain               text           NOT NULL DEFAULT 'solana',
  bonded_agent_wallet text           NOT NULL,
  beneficiary         text           NOT NULL,
  task_ref            text,
  amount              numeric(20, 6) NOT NULL DEFAULT '0',
  currency            text           NOT NULL DEFAULT 'USDC',
  status              text           NOT NULL DEFAULT 'open',
  escrow_ref          text           NOT NULL,
  resolution_proof_tx text,
  is_demo             boolean        NOT NULL DEFAULT false,
  opened_at           timestamptz    NOT NULL DEFAULT now(),
  resolved_at         timestamptz,
  CONSTRAINT bonds_chain_bonded_agent_wallet_fkey
    FOREIGN KEY (chain, bonded_agent_wallet)
    REFERENCES wallets (chain, address)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bonds_chain_bonded_agent_wallet
  ON bonds (chain, bonded_agent_wallet);
CREATE INDEX IF NOT EXISTS idx_bonds_status
  ON bonds (status);
CREATE INDEX IF NOT EXISTS idx_bonds_escrow_ref
  ON bonds (escrow_ref);
-- One projected row per (chain, escrow_ref) — dedup escrow events on re-index.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_bonds_escrow_ref
  ON bonds (chain, escrow_ref);

-- --- bond_underwriters ------------------------------------------------------
-- Stakers behind a bond. Surety Karma derives from their settled outcomes.

CREATE TABLE IF NOT EXISTS bond_underwriters (
  id                 uuid           PRIMARY KEY DEFAULT gen_random_uuid(),
  bond_id            uuid           NOT NULL REFERENCES bonds (id) ON DELETE CASCADE,
  chain              text           NOT NULL DEFAULT 'solana',
  underwriter_wallet text           NOT NULL,
  stake_amount       numeric(20, 6) NOT NULL DEFAULT '0',
  premium_earned     numeric(20, 6),
  settled            boolean        NOT NULL DEFAULT false,
  created_at         timestamptz    NOT NULL DEFAULT now(),
  CONSTRAINT bond_underwriters_chain_underwriter_wallet_fkey
    FOREIGN KEY (chain, underwriter_wallet)
    REFERENCES wallets (chain, address)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bond_underwriters_bond_id
  ON bond_underwriters (bond_id);
CREATE INDEX IF NOT EXISTS idx_bond_underwriters_chain_underwriter_wallet
  ON bond_underwriters (chain, underwriter_wallet);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_bond_underwriters
  ON bond_underwriters (bond_id, chain, underwriter_wallet);

COMMIT;
