/**
 * Sync x402 facilitator addresses from Merit-Systems/x402scan
 *
 * Fetches each facilitator definition from the upstream repo, extracts the
 * Solana addresses, and rewrites src/config/facilitators.ts in place.
 *
 * Usage:
 *   bun run sync:facilitators           # write changes
 *   bun run sync:facilitators --check   # fail with diff summary if stale
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'Merit-Systems/x402scan';
const BRANCH = 'main';
const FAC_DIR = 'packages/external/facilitators/src/facilitators';
const ALL_LIST_PATH = `${FAC_DIR}/../lists/all.ts`;
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(SCRIPT_DIR, '../config/facilitators.ts');

const RAW = (path: string) => `https://raw.githubusercontent.com/${REPO}/${BRANCH}/${path}`;

interface FacilitatorEntry {
  id: string;
  addresses: string[];
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status} ${res.statusText}`);
  return res.text();
}

/** Pull the ordered list of facilitator import names from lists/all.ts. */
async function getFacilitatorFileIds(): Promise<string[]> {
  const src = await fetchText(RAW(ALL_LIST_PATH));
  const match = src.match(/import\s*\{([\s\S]*?)\}\s*from\s*['"]\.\.\/facilitators['"]/);
  if (!match) throw new Error('Could not find facilitator imports in all.ts');
  const ids: string[] = [];
  for (const raw of match[1].split(',')) {
    const name = raw.trim().replace(/Facilitator$/, '');
    if (name) ids.push(name);
  }
  return ids;
}

/** Parse a single facilitator file and extract Solana addresses. */
function extractFromSource(src: string, fallbackId: string): FacilitatorEntry {
  const idMatch = src.match(/id:\s*['"]([^'"]+)['"]/);
  const id = idMatch?.[1] ?? fallbackId;

  // Locate the [Network.SOLANA]: [...] block. Use a small hand-rolled bracket
  // walker so nested braces in address entries don't break us.
  const key = '[Network.SOLANA]';
  const keyIdx = src.indexOf(key);
  if (keyIdx === -1) return { id, addresses: [] };

  const openIdx = src.indexOf('[', keyIdx + key.length);
  if (openIdx === -1) return { id, addresses: [] };

  let depth = 0;
  let closeIdx = -1;
  for (let i = openIdx; i < src.length; i++) {
    const ch = src[i];
    if (ch === '[') depth++;
    else if (ch === ']') {
      depth--;
      if (depth === 0) {
        closeIdx = i;
        break;
      }
    }
  }
  if (closeIdx === -1) return { id, addresses: [] };

  const block = src.slice(openIdx, closeIdx + 1);
  const addresses = new Set<string>();
  for (const m of block.matchAll(/address:\s*['"]([1-9A-HJ-NP-Za-km-z]{32,44})['"]/g)) {
    addresses.add(m[1]);
  }

  return { id, addresses: [...addresses] };
}

function renderConfigFile(entries: FacilitatorEntry[]): string {
  const withAddrs = entries
    .filter((e) => e.addresses.length > 0)
    .sort((a, b) => a.id.localeCompare(b.id));

  const body = withAddrs
    .map((e) => {
      if (e.addresses.length === 1) {
        return `  ${e.id}: ['${e.addresses[0]}'],`;
      }
      const lines = e.addresses.map((a) => `    '${a}',`).join('\n');
      return `  ${e.id}: [\n${lines}\n  ],`;
    })
    .join('\n');

  return `/**
 * Known x402 facilitator addresses on Solana
 * Source: github.com/Merit-Systems/x402scan
 *
 * Auto-generated by \`bun run sync:facilitators\`. Do not edit by hand —
 * run the sync script to pull the latest entries from upstream.
 */

export const SOLANA_FACILITATORS: Record<string, string[]> = {
${body}
};

export const ALL_FACILITATOR_ADDRESSES = Object.values(SOLANA_FACILITATORS).flat();
export const USDC_MINT = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';

export function isX402Payment(recipient: string): boolean {
  return ALL_FACILITATOR_ADDRESSES.includes(recipient);
}

export function getFacilitatorName(address: string): string | null {
  for (const [name, addresses] of Object.entries(SOLANA_FACILITATORS)) {
    if (addresses.includes(address)) return name;
  }
  return null;
}
`;
}

async function main() {
  const check = process.argv.includes('--check');

  const fileIds = await getFacilitatorFileIds();
  console.log(`[sync] upstream lists ${fileIds.length} facilitators`);

  const entries: FacilitatorEntry[] = [];
  let idx = 0;
  // JS identifiers can't start with digits, so upstream prefixes numeric
  // filenames with `f` (e.g. `402104.ts` → `f402104Facilitator`). Try both.
  const candidatePaths = (fileId: string) => {
    const out = [`${FAC_DIR}/${fileId}.ts`];
    if (/^f\d/.test(fileId)) out.push(`${FAC_DIR}/${fileId.slice(1)}.ts`);
    return out;
  };

  for (const fileId of fileIds) {
    idx++;
    let src: string | null = null;
    let lastErr: Error | null = null;
    for (const path of candidatePaths(fileId)) {
      try {
        src = await fetchText(RAW(path));
        break;
      } catch (err) {
        lastErr = err as Error;
      }
    }
    if (!src) {
      console.warn(`  [${idx}/${fileIds.length}] ${fileId}: skipped (${lastErr?.message})`);
      continue;
    }
    const entry = extractFromSource(src, fileId);
    entries.push(entry);
    console.log(`  [${idx}/${fileIds.length}] ${entry.id}: ${entry.addresses.length} Solana addr`);
  }

  const next = renderConfigFile(entries);
  const current = await readFile(TARGET, 'utf8').catch(() => '');

  if (current.trim() === next.trim()) {
    console.log('[sync] facilitators.ts already up to date');
    return;
  }

  if (check) {
    const currentAddrs = new Set(current.match(/['"]([1-9A-HJ-NP-Za-km-z]{32,44})['"]/g) ?? []);
    const nextAddrs = new Set(next.match(/['"]([1-9A-HJ-NP-Za-km-z]{32,44})['"]/g) ?? []);
    const added = [...nextAddrs].filter((a) => !currentAddrs.has(a));
    const removed = [...currentAddrs].filter((a) => !nextAddrs.has(a));
    console.error(`[sync] OUT OF DATE — added ${added.length}, removed ${removed.length}`);
    if (added.length) console.error('  +', added.join('\n  + '));
    if (removed.length) console.error('  -', removed.join('\n  - '));
    process.exit(1);
  }

  await writeFile(TARGET, next);
  const totalAddrs = entries.reduce((sum, e) => sum + e.addresses.length, 0);
  console.log(`[sync] wrote ${TARGET} (${entries.filter((e) => e.addresses.length).length} facilitators, ${totalAddrs} addresses)`);
}

main().catch((err) => {
  console.error('[sync] fatal:', err);
  process.exit(1);
});
