/**
 * Specimen agent addresses — kept separate from facilitators.ts because
 * that file is auto-regenerated by `bun run sync:facilitators`.
 *
 * The specimen runs a real x402-style USDC micro-API on mainnet so we can
 * exercise the full pipeline (payment → indexer → scoring → 8004 attestation)
 * end-to-end against actual on-chain state, instead of synthetic data.
 *
 * The provider wallet receives every consumer payment, so it shows up as the
 * counterparty in extractX402Payment(). Listing it here makes the indexer
 * iterate it like any other facilitator.
 */

export const SPECIMEN_PROVIDER_ADDRESS = 'BfqzVwCcNf1TcVyYaZr6zjjeZKFt57fMDMcRKGjTqQCm';
export const SPECIMEN_CONSUMER_ADDRESS = 'AwHpZNJA1PyWGSsqbMhFcgyJRR1bYvQTnq2DtH8ud7uZ';

/** USDC price per /echo call, in human units (NOT raw). 1 USDC = 10^6 raw. */
export const SPECIMEN_PRICE_USDC = 0.001;

/** Tolerance window: how recent must the payment tx be to be accepted. */
export const SPECIMEN_PAYMENT_MAX_AGE_SEC = 120;

export const SPECIMEN_FACILITATOR_LABEL = 'agentkarma-specimen';

export const SPECIMEN_ADDRESSES = [SPECIMEN_PROVIDER_ADDRESS] as const;
